### ISSUE TITLE
Limitation issue about inputs in output nodes

### ISSUE THREAD

**Issue by jonnynux** [PaloAltoNetworks/minemeld-webui#111]
Hi, 
i've seen there is a limitation about inputs I can choose from the web interface in output nodes, but I can bypass this limitation editing the config file of the nodes. I thin this is a web interface limitation.

Thank you,
Giorgio

**Comment by jtschichold** [comment]
Hi @jonnynux,
sorry for the late reply. Yes, it's a way to prevent mistakes on the WebUI. If you click on the "eye" icon on the input dialog, you will switch to expert mode and you can add more inputs.

Thanks,
luigi
