### ISSUE TITLE
Support for client cert in TAXII Miner

### ISSUE THREAD

**Issue by jtschichold** [PaloAltoNetworks/minemeld-webui#95]
Currently the only way to supply a client cert to TAXII Miner is via shell. We should support this via WebUI.

User should be able to:
- upload client certificate to TAXII Miner
- remove current client certificate

**Comment by jtschichold** [comment]
Implemented in 0.9.36

**Comment by rmeghnagi** [comment]
Hi @jtschichold 

how can i link the .crt and .key files inside the prototype of a miner to retrieve content?
